<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit205d620e6d89b9ac87cc9a9b12a7d6fb
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
        'D' => 
        array (
            'DocuSign\\eSign\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
        'DocuSign\\eSign\\' => 
        array (
            0 => __DIR__ . '/..' . '/docusign/esignclient/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit205d620e6d89b9ac87cc9a9b12a7d6fb::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit205d620e6d89b9ac87cc9a9b12a7d6fb::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
